AWSTemplateFormatVersion: '2010-09-09'
Description: Database Stack

Resources:
  DjangoDBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable MySQL access
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue EC2SecurityGroup

  DjangoDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: masteruser
      MasterUserPassword: masterpassword
      DBName: djangodb
      VPCSecurityGroups:
        - !Ref DjangoDBSecurityGroup
      SubnetGroupName: !Ref DBSubnetGroup

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !ImportValue PrivateSubnetId

Outputs:
  DjangoDBEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt DjangoDB.Endpoint.Address
