AWSTemplateFormatVersion: '2010-09-09'
Description: Networking Stack

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: true

  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.2.0/24'

Outputs:
  VPCId:
    Description: VPC Id
    Value: !Ref VPC

  PublicSubnetId:
    Description: Public Subnet Id
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: Private Subnet Id
    Value: !Ref PrivateSubnet
